package com.example.grupparbete_backend_1.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class MailController {

    @Autowired
    JavaMailSender mailSender;

    @GetMapping("/send-email")
    String sendEmail() {
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom("Autogenerated@pensionat-booking.com");
        message.setTo("testis@testson.com");
        message.setSubject("Test subject ");
        message.setText("Grupparbete test");
        mailSender.send(message);


        return "Grupparbete";


    }
}
