package com.example.grupparbete_backend_1.controllers;

import com.example.grupparbete_backend_1.dto.MailRequestDto;
import com.example.grupparbete_backend_1.services.EmailingService;
import jakarta.mail.MessagingException;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;


@RequiredArgsConstructor
@RestController
@RequestMapping("/api/v1/mail")
public class MailController {

    /*@Autowired
    JavaMailSender mailSender;

    @GetMapping("/send-email")
    String sendEmail() {
        SimpleMailMessage message = new SimpleMailMessage();
        message.setFrom("Autogenerated@pensionat-booking.com");
        message.setTo("testis@testson.com");
        message.setSubject("Test subject ");
        message.setText("Grupparbete test");
        mailSender.send(message);


        return "Grupparbete";


    }*/

    private final EmailingService emailingService;

    @GetMapping
    @ResponseStatus(HttpStatus.OK)
    public void SendMail() throws MessagingException {

        MailRequestDto mailRequestDto1 = new MailRequestDto("autogenerated@pensionat.se","test@test1.se", "qweqw", "12312", true);

        emailingService.sendEmail(mailRequestDto1);

    }


}
